server:
  port: 8088
spring:
  application:
    name: jltc
  pid:
    file: ${spring.application.name}.pid
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.4.100:3306/test_sql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
logging:
  level:
    me.group.demo.mbp.example: debug
  file:
    name: ${spring.application.name}.log
#  mybatis.mapper-locations=classpath:mapper/*.xml
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: top.jltc.server.model.assembly
